# Plenum CRM Status Page
# Powered by Upptime (https://upptime.js.org)

owner: paradixe
repo: plenum-status

sites:
  - name: Plenum CRM
    url: https://plenum.pro
  - name: Plenum API
    url: https://plenum.pro/api/health
  - name: Supabase API
    url: https://supabase.plenum.pro

status-website:
  cname: status.plenum.pro
  logoUrl: https://plenum.pro/logo.png
  name: Plenum Status
  introTitle: "**Plenum** is the complete HVAC business operating system"
  introMessage: This is the status page for Plenum CRM services. We monitor our services every 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: Plenum CRM
      href: https://plenum.pro

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
